chain_id: chain1
version: "2030600"
sequence: 0
auth_type: permissionedWithCert
crypto:
  hash: SHA256
contract:
  enable_sql_support: false
vm:
  addr_type: 2
  support_list:
  - wasmer
  - gasm
  - evm
  - dockergo
  - wxvm
block:
  tx_timestamp_verify: true
  tx_timeout: 600
  block_tx_capacity: 100
  block_size: 500
  block_interval: 10
  tx_parameter_size: 50
core:
  tx_scheduler_timeout: 0
  tx_scheduler_validate_timeout: 10
  enable_sender_group: false
  enable_conflicts_bit_window: true
snapshot: null
scheduler: null
account_config:
  enable_gas: false
  gas_count: 0
  default_gas: 100
consensus:
  type: 0
  nodes:
  - org_id: TestCMorg1
    node_id:
    - QmQMsfF9iBzSC6EFpHPE7YQMY9BbG3Utt3DdneBViKpSPF
  ext_config: []
trust_roots:
- org_id: TestCMorg1
  root:
  - ../config/certs/ca/TestCMorg1/ca.crt
resource_policies:
- resource_name: CHAIN_CONFIG-NODE_ID_UPDATE
  policy:
    rule: SELF
    org_list: []
    role_list:
    - admin
- resource_name: CHAIN_CONFIG-TRUST_ROOT_ADD
  policy:
    rule: MAJORITY
    org_list: []
    role_list:
    - admin
- resource_name: CHAIN_CONFIG-CERTS_FREEZE
  policy:
    rule: ANY
    org_list: []
    role_list:
    - admin
- resource_name: CONTRACT_MANAGE-INIT_CONTRACT
  policy:
    rule: ANY
    org_list: []
    role_list: []
